
TOP = ../../..
include $(TOP)/Make.misc

BASE_MAN8 = lim.8 lsfinstall.8 nios.8 res.8 eauth.8 lsadmin.8 pim.8

install:
	mkdir -p $(OPENLAVA_MANDIR)/man8 ; \
	install -c -m 644 $(BASE_MAN8) $(OPENLAVA_MANDIR)/man8
