#!/bin/sh

echo a| awk '{for (i = 0; i < 1021; i++)
               {printf "host%d IntelI5 linux 1 3.5 (cs)\n", i}}' > clus
echo a| awk '{for (i = 2; i <= 5; i++) 
                  {for (j = 0; j < 255; j++) 
                     {printf "192.168.%d.%d host%d\n", i, j, k++}}}' > hosts
