#!/bin/sh

##
## Start and stop Lava daemons
##

# The following is for the Linux chkconfig utlility
# chkconfig: 35 99 01
# description:  Load Sharing Facility

#
### BEGIN INIT INFO
# Provides: lava
# Required-Start: $local_fs $remote_fs $syslog
# Required-Stop: $local_fs $remote_fs $syslog
# Short-Description: Load Sharing Facility
# Description: Load Sharing Facility
### END INIT INFO


# This is the root of oepn lava installation
# change it if installed somewhere else.
export LAVA_TOP=__LAVATOP__

# kill the old daemons first.
#
kill_daemons()
{
    killall -v lim res sbatchd  mbatchd
}

case "$1" in
  'stop')
        kill_daemons
        exit 0
        ;;

  'start')
        LSF_CONF=$LAVA_TOP/conf/lsf.conf

        if [ -f $LSF_CONF ]
        then
            echo "Checking if daemons are still alive..."
            kill_daemons

            # Get the location of the Lava daemons
            . $LSF_CONF

            # Export this env.variable to notify Lava daemons the loc. of
            # lsf.conf
            export LSF_ENVDIR
            export LSF_SERVERDIR
            echo "Starting daemons..."

	    ID=`id -u`
            if [ "$ID" != 0 ]; then
            # single user mode use this
            # to run test clusters
               $LSF_SERVERDIR/lim -1
               echo "lim -1 started"
               $LSF_SERVERDIR/res -1
               echo "res -1 started"
               $LSF_SERVERDIR/sbatchd -1
               echo "sbatchd -1 started"
            else 
               # multi user mode
               $LSF_SERVERDIR/lim
               echo "lim started"
               $LSF_SERVERDIR/res
               echo "res started"
               $LSF_SERVERDIR/sbatchd
               echo "sbatchd started"
            fi
            exit 0
        fi
        echo "$LSF_CONF: no such file or directory"
        exit 1
        ;;
  'status')
        PID=`pidof lim`
        echo "lim pid: <$PID>"
        PID=`pidof res`
        echo "res pid: <$PID>"
        PID=`pidof sbatchd`
        echo "sbatchd pid: <$PID>"
        PID=`pidof mbatchd`
        echo "lim mbatchd: <$PID>"
        exit 0
        ;;
  'restart')
        echo "Stop lava and start for restarting the services"
        ;;
  *)
        echo "Script for starting up and shutting down lava"
        echo "Usage: $0 { start | stop | status | restart }"
        exit 0
        ;;
esac

