.ds ]W %
.ds ]L
.nh
.TH bparams 1 "Lava Version 1.0 - Sept 2007"
.br
.SH NAME
\fBbparams\fR - displays information about configurable system parameters in 
lsb.params
.SH SYNOPSIS
.BR
.PP
.PP
\fBbparams\fR [\fB-l\fR] 
.PP
\fBbparams\fR [\fB-h\fR | \fB-V\fR]
.SH DESCRIPTION
.BR
.PP
.PP
\fB\fRDisplays information about configurable system parameters in 
lsb.params. 
.PP
By default, displays only the interesting parameters.
.SH OPTIONS
.BR
.PP
.TP 
\fB-l
\fR
.IP
Long format. Displays detailed information about all the configurable 
parameters in lsb.params.


.TP 
\fB-h
\fR
.IP
Prints command usage to stderr and exits. 


.TP 
\fB-V
\fR
.IP
Prints Lava release version to stderr and exits. 


.SH SEE ALSO
.BR
.PP
.PP
lsb.params(5)
